### ISSUE TITLE
pip install 0-core-client fails on Windows

### ISSUE THREAD

**Issue by yveskerwyn** [zero-os/0-core#352]
Running version 3.6.1 Python 64 bit Windows

```
C:\Users\arne.vanbalgoijen\AppData\Local\Programs\Python\Python36\Scripts> .\pip install 0-core-client
Collecting 0-core-client
  Using cached 0-core-client-1.1.0a4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ARNE~1.VAN\AppData\Local\Temp\pip-build-cemg6xlh\0-core-client\setup.py", line 9, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "c:\users\arne.vanbalgoijen\appdata\local\programs\python\python36\lib\codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ARNE~1.VAN\\AppData\\Local\\Temp\\pip-build-cemg
6xlh\\0-core-client\\README.md'
```

```
Command "python setup.py egg_info" failed with error code 1 in C:\Users\ARNE~1.VAN\AppData\Local\Temp\pip-build-cemg6xlh
```

**Comment by FastGeert** [comment]
Fixed in 0cb4680fdbd38da35f2e58eb699c982afc19dce0

**Comment by ahussein** [comment]
Just FYI, we also had the same failure when linking the python client as a dependency to one of the js9 package. Installation of the package via pip failed with the same error above but on a Linux system.

**Comment by ahmedelsayed-93** [comment]
### software version
master : 933434
