### ISSUE TITLE
tags argument doesn't exist in  container info  

### ISSUE THREAD

**Issue by Dinaamagdy** [zero-os/0-core#408]
## Issue 
there is no tag argument in container info ,so gw with vlan network creation from orchestrator doesn't work  as it search about ovs tag as shown  . 
```
Error of job: container!ZB12 (install):
*TRACEBACK*********************************************************************************
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/1a3c2c490814fe3e23186abf76faca03.py", line 60, in install
    j.tools.async.wrappers.sync(job.service.executeAction('start', context=job.context))
  File "/opt/code/github/jumpscale/lib9/JumpScale9Lib/tools/async/Wrappers.py", line 12, in sync
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 679, in executeAction
    return await self.executeActionJob(action, args, context=context)
  File "/opt/code/github/jumpscale/ays9/JumpScale9AYS/ays/lib/Service.py", line 704, in executeActionJob
    result = await job.execute()
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/actions/container/1a3c2c490814fe3e23186abf76faca03.py", line 129, in start
    container.start()
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 190, in start
    if not self.is_running():
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 212, in is_running
    return self.id is not None
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 122, in id
    info = self.info
  File "/usr/local/lib/python3.5/dist-packages/zeroos/orchestrator/sal/Container.py", line 131, in info
    if self.name in (container['container']['arguments']['tags'] or []):
KeyError: 'tags'

```

**Comment by Dinaamagdy** [comment]
## Software Version
9c15a60eef11d61f975d73182ddaaac0dfdbae93
