### ISSUE TITLE
zrobot wouldn't start on ZOS

### ISSUE THREAD

**Issue by katia-e** [zero-os/0-core#683]
0-robot issue: https://github.com/zero-os/0-robot/issues/193

have error when trying to access robot:
![image](https://user-images.githubusercontent.com/32639869/40606783-d073352e-6266-11e8-8421-381df46a9b1d.png)

Error from the container: 
``` py
node = j.clients.zos.sal.get_node(instance='zos')
node.containers.list()[0].client.subscribe('zrobot').stream()
```
![image](https://user-images.githubusercontent.com/32639869/40606838-f922a9fa-6266-11e8-91b7-daba786a9af7.png)

Steps to reproduce:
1. run ZOS locally from development
``` sh
 qemu-img create -f qcow2 vda.qcow2 10G
 sudo qemu-system-x86_64 -kernel zero-os-development.efi -m 2048 -enable-kvm -cpu host -append "console=ttyS0,115200n8 development zerotier=$ZEROTIER" -netdev bridge,id=virbr0,br=virbr0 -device virtio-net-pci,netdev=virbr0 -hda vda.qcow2
```

2. get zrobot client and try to access the list of services:
``` py
robot = j.clients.zrobot.robots["zos_local_robot"]
robot.services.names
```

**Comment by Dinaamagdy** [comment]
Full error stack trace
```
STDERR:
Traceback (most recent call last):
  File "usr/local/bin/zrobot", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/opt/code/github/zero-os/0-robot/cmd/zrobot", line 25, in <module>
    entry_point()
  File "/opt/code/github/zero-os/0-robot/zerorobot/cli/server.py", line 71, in start
    robot.set_config_repo(config_repo, config_key)
  File "/opt/code/github/zero-os/0-robot/zerorobot/robot/robot.py", line 80, in set_config_repo
    config_repo.init(path, key)
  File "/opt/code/github/zero-os/0-robot/zerorobot/robot/config_repo.py", line 54, in init
    j.tools.configmanager.init(silent=True, configpath=path, keypath=key)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/ConfigManager.py", line 432, in init
    j.clients.sshkey.key_get(keypath, load=True)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/sshkey/SSHKeys.py", line 25, in key_get
    sshkey = self.get(instance, data={'path': path}, interactive=j.tools.configmanager.interactive)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/JSBaseClassConfigs.py", line 43, in get
    return self._child_class(instance=instance, data=data, parent=self, interactive=interactive,**kwargs)
  File "/opt/code/github/jumpscale/core9/JumpScale9/clients/sshkey/SSHKey.py", line 23, in __init__
    parent=parent, template=TEMPLATE, interactive=interactive)
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/configmanager/JSBaseClassConfig.py", line 16, in __init__
    self._ui = j.tools.formbuilder.baseclass_get()  # is the default class
  File "/usr/lib/python3/dist-packages/js9.py", line 1524, in formbuilder
    from JumpScale9.tools.formbuilder.FormBuilder import FormBuilderFactory as FormBuilderFactory
  File "/opt/code/github/jumpscale/core9/JumpScale9/tools/formbuilder/FormBuilder.py", line 3, in <module>
    import npyscreen
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/__init__.py", line 5, in <module>
    from .wgwidget                  import TEST_SETTINGS, ExhaustedTestInput, add_test_input_from_iterable, add_test_input_ch
  File "/usr/local/lib/python3.5/dist-packages/npyscreen/wgwidget.py", line 5, in <module>
    import curses
  File "/usr/lib/python3.5/curses/__init__.py", line 13, in <module>
    from _curses import *
ImportError: /lib/x86_64-linux-gnu/libncursesw.so.5: symbol LINES, version NCURSES_TINFO_5.0.19991023 not defined in file libtinfo.so.5 with link time reference
[Mon28 11:03] - ErrorHandler.py   :257 :j.core.errorhandler  - ERROR    - /lib/x86_64-linux-gnu/libncursesw.so.5: symbol LINES, version NCURSES_TINFO_5.0.19991023 not defined in file libtinfo.so.5 with link time reference

DATA:
```

**Comment by muhamadazmy** [comment]
Some findings:
- After the container is started (but zrobot process still fails) a hack to make it work is to `touch` the libtinfo file !
```python
#container is a client container.
container.system('touch /lib/x86_64-linux-gnu/libtinfo.so.5.9').get()
```
The reason that this work is `unknown` but we know the following
- Access time of a file inside 0-fs was set to epoch 0 before, we fixed that to report the time the 0-fs process was started rounded to nearest second (this did not fix the problem) 
- On a working zrobot instance the access time of the libtinfo.so.5.9  has the nsec part set to a NONE ZERO value which is weird because this is not how the time is returned from 0-fs (round to nearest second as mentioned before)
- On a NON working zrobot instance, the access time of the libtinfo.so.5. has nset part set to 0 as returned by 0-fs.
- A touch does 2 things
  - It moves the file to the RW layer of the overlay filesystem
  - It updates the access time

**Comment by muhamadazmy** [comment]
Also what the hick is a `link time reference` ?! I can't find any resource that explain this.

**Comment by muhamadazmy** [comment]
@zaibon should we close this as "un-fixable" ?

**Comment by zaibon** [comment]
I guess I can close it here and keep the issue open in 0-robot.
