### ISSUE TITLE
Some error while creating btrfs using loop devices

### ISSUE THREAD

**Issue by john-kheir** [zero-os/0-core#725]
## Getting these errors from time to time .. No idea why this happens.

1- `Unable to determine size of /dev/loop4`
```Traceback (most recent call last):
  File "/root/0-core/tests/testsuite/b_extended/tests_01_disks.py", line 553, in test009_btrfs_add_remove_devices
    self.client.btrfs.device_add(self.mount_point, d1)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 2031, in device_add
    self._client.sync('btrfs.device_add', args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 786, in sync
    raise ResultError(msg='%s' % result.data, code=result.code)
zeroos.core0.client.client.ResultError: "(ERROR): [ ERROR: unable to determine size of /dev/loop4\n]"
```
2- `No such file or directory`
```
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/0-core/tests/testsuite/b_extended/tests_01_disks.py", line 543, in test009_btrfs_add_remove_devices
    self.create_btrfs(second_btrfs=True)
  File "/root/0-core/tests/testsuite/b_extended/tests_01_disks.py", line 33, in create_btrfs
    self.client.btrfs.create(self.label2, self.loop_dev_list2, overwrite=True)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 2011, in create
    self._client.sync('btrfs.create', args)
  File "/usr/local/lib/python3.5/dist-packages/zeroos/core0/client/client.py", line 786, in sync
    raise ResultError(msg='%s' % result.data, code=result.code)
zeroos.core0.client.client.ResultError: "(ERROR): [btrfs-progs v4.19 \nSee http://btrfs.wiki.kernel.org for more information.\n\n ERROR: mount check: cannot open : No such file or directory\nERROR: cannot check mount status of : No such file or directory\n]"

```

**Comment by john-kheir** [comment]
moved to https://github.com/threefoldtech/0-core/issues/121
